services:
  postgres:
    image: postgres:16-alpine
    container_name: users-postgres-upm
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users -d usersdb"]
      interval: 5s
      timeout: 5s
      retries: 10
